---
apiVersion: v2
version: 0.16.0
appVersion: "0.16.0"
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: teocns
name: redis-operator
sources:
  - https://github.com/teocns/redis-operator
home: https://github.com/teocns/redis-operator
icon: https://github.com/teocns/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
dependencies:
  - name: cert-manager
    version: v1.12.4
    repository: https://charts.jetstack.io
    alias: certmanager
    condition: certmanager.enabled
